#!/usr/bin/env node

const cli = require('commander');
const { jumpstart } = require('./index');

function main() {
  cli
    .name('jumpstart')
    .option('--check-only')
    .action((name, options) => {
      jumpstart(options);
    //   console.error("test")
    });
  cli.parse(process.argv);
}

main();

module.exports = { main };
