#!/usr/bin/env node

const cli = require('commander');
const { jumpstart } = require('./index');

cli
  .name('jumpstart')
  .option('--check-only')
  .action(() => {
    jumpstart();
  });

cli.parse(process.argv);
